name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore Auth0.MyOrganizationApi.sln

      - name: Build
        run: dotnet build Auth0.MyOrganizationApi.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/Auth0.MyOrganizationApi.Test/Auth0.MyOrganizationApi.Test.csproj --collect:"XPlat Code coverage" --results-directory ./TestResults/ /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Update codecov report
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # pin@7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/**/coverage.cobertura.xml
          fail_ci_if_error: false
          verbose: true
